"""
Spider settings for BiliDownloader project.
Generated by 'yejue' using his hand.
"""

import os


# 建立项目根目录
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# 建立视频默认存储路径
SAVE_PATH = os.path.join(BASE_DIR, 'static/video')
